CREATE TABLE `avgtime20170901` (
	`START_STATION` VARCHAR (20) NOT NULL,
	`END_STATION` VARCHAR (20) NOT NULL,
	`DIRECTION` VARCHAR (10) DEFAULT NULL,
	`DURATION` INT (11) DEFAULT NULL,
	`DISTANCE` FLOAT DEFAULT NULL,
	`TIME` VARCHAR (20) DEFAULT NULL,
	`ISBUS` VARCHAR (10) DEFAULT NULL,
	PRIMARY KEY (
		`START_STATION`,
		`END_STATION`
	)
) ENGINE = INNODB DEFAULT CHARSET = utf8
CREATE TABLE `avgtime20170908` (
	`START_STATION` VARCHAR (20) NOT NULL,
	`END_STATION` VARCHAR (20) NOT NULL,
	`DIRECTION` VARCHAR (10) DEFAULT NULL,
	`DURATION` INT (11) DEFAULT NULL,
	`DISTANCE` FLOAT DEFAULT NULL,
	`TIME` VARCHAR (20) DEFAULT NULL,
	`ISBUS` VARCHAR (10) DEFAULT NULL,
	PRIMARY KEY (
		`START_STATION`,
		`END_STATION`
	)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
CREATE TABLE `avgtime20170915` (
	`START_STATION` VARCHAR (20) NOT NULL,
	`END_STATION` VARCHAR (20) NOT NULL,
	`DIRECTION` VARCHAR (10) DEFAULT NULL,
	`DURATION` INT (11) DEFAULT NULL,
	`DISTANCE` FLOAT DEFAULT NULL,
	`TIME` VARCHAR (20) DEFAULT NULL,
	`ISBUS` VARCHAR (10) DEFAULT NULL,
	PRIMARY KEY (
		`START_STATION`,
		`END_STATION`
	)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
CREATE TABLE `avgtime20170922` (
	`START_STATION` VARCHAR (20) NOT NULL,
	`END_STATION` VARCHAR (20) NOT NULL,
	`DIRECTION` VARCHAR (10) DEFAULT NULL,
	`DURATION` INT (11) DEFAULT NULL,
	`DISTANCE` FLOAT DEFAULT NULL,
	`TIME` VARCHAR (20) DEFAULT NULL,
	`ISBUS` VARCHAR (10) DEFAULT NULL,
	PRIMARY KEY (
		`START_STATION`,
		`END_STATION`
	)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
CREATE TABLE `avgtime20170929` (
	`START_STATION` VARCHAR (20) NOT NULL,
	`END_STATION` VARCHAR (20) NOT NULL,
	`DIRECTION` VARCHAR (10) DEFAULT NULL,
	`DURATION` INT (11) DEFAULT NULL,
	`DISTANCE` FLOAT DEFAULT NULL,
	`TIME` VARCHAR (20) DEFAULT NULL,
	`ISBUS` VARCHAR (10) DEFAULT NULL,
	PRIMARY KEY (
		`START_STATION`,
		`END_STATION`
	)
) ENGINE = INNODB DEFAULT CHARSET = utf8