-- 去除错误匹配数据.WHEN TICKET_ID, START_TIME相同时，
-- 还存在TICKET_ID, END_TIME相同时，未考虑
SELECT
	A.TICKET_ID,
	A.START_TIME,
	A.END_TIME
FROM
	od20170930 AS A
WHERE
	(A.TICKET_ID, A.START_TIME) IN (
		SELECT
			B.TICKET_ID,
			B.START_TIME
		FROM
			od20170930 AS B
		GROUP BY
			B.TICKET_ID,
			B.START_TIME
		HAVING
			count(B.TICKET_ID) > 1
	)
AND (
	A.TICKET_ID,
	A.START_TIME,
	A.END_TIME
) NOT IN (
	SELECT
		BB.TICKET_ID,
		BB.START_TIME,
		BB.END_TIME
	FROM
		od20170930 AS BB
	WHERE
		(
			BB.TICKET_ID,
			BB.START_TIME,
			BB.END_TIME
		) IN (
			SELECT
				AA.TICKET_ID,
				AA.START_TIME,
				AA.END_TIME
			FROM
				(
					SELECT
						C.TICKET_ID,
						C.START_TIME,
						MIN(C.END_TIME) AS END_TIME
					FROM
						od20170930 AS C
					GROUP BY
						C.TICKET_ID,
						C.START_TIME
					HAVING
						COUNT(*) > 1
				) AS AA
		)
)